"""Add promo_code_id to Payment

Revision ID: 90f92fc840e2
Revises: 2e1000b12958
Create Date: 2026-02-11 14:47:10.483730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f92fc840e2'
down_revision: Union[str, Sequence[str], None] = '2e1000b12958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promo_code_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_payments_promo_code_id', 'promo_codes', ['promo_code_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_promo_code_id', type_='foreignkey')
        batch_op.drop_column('promo_code_id')

    # ### end Alembic commands ###
