"""Add referrer_id to User

Revision ID: d811389c984c
Revises: 90f92fc840e2
Create Date: 2026-02-11 21:49:34.324782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd811389c984c'
down_revision: Union[str, Sequence[str], None] = '90f92fc840e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referrer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_referrer_id', 'users', ['referrer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_referrer_id', type_='foreignkey')
        batch_op.drop_column('referrer_id')

    # ### end Alembic commands ###
