"""Add notification_status

Revision ID: fb6df8db9fe9
Revises: d811389c984c
Create Date: 2026-02-11 23:22:21.286418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6df8db9fe9'
down_revision: Union[str, Sequence[str], None] = 'd811389c984c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dns_access', schema=None) as batch_op:
        pass
        # batch_op.add_column(sa.Column('notification_status', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('vpn_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_status', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vpn_keys', schema=None) as batch_op:
        batch_op.drop_column('notification_status')

    with op.batch_alter_table('dns_access', schema=None) as batch_op:
        batch_op.drop_column('notification_status')

    # ### end Alembic commands ###
